name: Sync labels
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          manifest: 'https://raw.githubusercontent.com/pyansys-testing/workflows/main/.github/workflows/labels.yml'
